# Copyright (c) 2024 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GNU LGPL v2.1 or later

version: 2
updates:

  - package-ecosystem: "github-actions"
    commit-message:
      include: "scope"
      prefix: "Actions"
    directory: "/"
    labels:
      - "enhancement"
    schedule:
      interval: "weekly"
